// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Game struct {
	ID         int32    `json:"id"`
	Name       string   `json:"name"`
	Surname    string   `json:"surname"`
	Price      string   `json:"price"`
	Desc       string   `json:"desc"`
	Link       string   `json:"link"`
	Release    string   `json:"release"`
	Platforms  string   `json:"platforms"`
	Genre      string   `json:"genre"`
	Developers string   `json:"developers"`
	Publishers string   `json:"publishers"`
	InCart     bool     `json:"inCart"`
	Selected   bool     `json:"selected"`
	IsHovered  bool     `json:"isHovered"`
	IsLiked    bool     `json:"isLiked"`
	Rating     int32    `json:"rating"`
	Cover      string   `json:"cover"`
	Footage    []string `json:"footage"`
}

type Library struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	GameID int32  `json:"game_id"`
}

type Payment struct {
	ID     string  `json:"id"`
	UserID string  `json:"user_id"`
	Price  float64 `json:"price"`
}

type PaymentGame struct {
	PaymentID string `json:"payment_id"`
	GameID    int32  `json:"game_id"`
}

type Role struct {
	Ticker   string `json:"ticker"`
	RoleName string `json:"role_name"`
}

type Session struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    int64     `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID         string `json:"id"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Avatar     string `json:"avatar"`
	RoleTicker string `json:"role_ticker"`
}
